Require Julia 1.3
On Julia 1.2, the ManyPencilArray constructor fails for a reason that I
don't understand. It seems to expect a different constructor signature
from the one that actually exists. Things work without any problem on
Julia 1.3.

Below is the error.

ManyPencilArray: Error During Test at /home/jpolanco/.julia/dev/PencilFFTs/test/pencils.jl:151
  Got exception outside of a @test
  MethodError: no method matching (::getfield(PencilFFTs.Pencils, Symbol("##ManyPencilArray#30#31")))(::Tuple{}, ::Type{ManyPencilArray}, ::Tuple{Pencil{3,2,Float64,Nothing},Pencil{3,2,Float64,Val{(2, 3, 1)}},Pencil{3,2,Float64,Val{(3, 2
, 1)}}})
  Closest candidates are:
    #ManyPencilArray#30(::Tuple{Vararg{Int64,N}} where N, ::Type{ManyPencilArray}, !Matched::Pencil{N,X,T,P} where P where X where N...) where {M, T} at /home/jpolanco/.julia/dev/PencilFFTs/src/Pencils/multiarrays.jl:28
  Stacktrace:
   [1] ManyPencilArray(::Pencil{3,2,Float64,Nothing}, ::Pencil{3,2,Float64,Val{(2, 3, 1)}}, ::Pencil{3,2,Float64,Val{(3, 2, 1)}}) at /home/jpolanco/.julia/dev/PencilFFTs/src/Pencils/multiarrays.jl:28
   [2] test_multiarrays(::Pencil{3,2,Float64,Nothing}, ::Pencil{3,2,Float64,Val{(2, 3, 1)}}, ::Pencil{3,2,Float64,Val{(3, 2, 1)}}) at /home/jpolanco/.julia/dev/PencilFFTs/test/pencils.jl:81
   [3] macro expansion at /home/jpolanco/.julia/dev/PencilFFTs/test/pencils.jl:152 [inlined]
   [4] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113 [inlined]
   [5] main() at /home/jpolanco/.julia/dev/PencilFFTs/test/pencils.jl:152
   [6] top-level scope at /home/jpolanco/.julia/dev/PencilFFTs/test/pencils.jl:325
   [7] include at ./boot.jl:328 [inlined]
   [8] include_relative(::Module, ::String) at ./loading.jl:1094
   [9] include(::Module, ::String) at ./Base.jl:31
   [10] exec_options(::Base.JLOptions) at ./client.jl:295
   [11] _start() at ./client.jl:464